spring.datasource.url=jdbc:postgresql://localhost:5432/vivekDB
spring.datasource.username=postgres
spring.datasource.password=vivek123
spring.datasource.driver-class-name=org.postgresql.Driver

# Max size of a single file
spring.servlet.multipart.max-file-size=50MB
# Max size of the complete request
spring.servlet.multipart.max-request-size=50MB

#Redis
spring.redis.host=localhost
spring.redis.port=6379
spring.cache.type=redis


#Queries
example.queries.selectAll = SELECT id, name, address, mobile_no AS mobileNo, salary, date_of_birth AS dob, is_active AS active FROM employee
example.queries.findById = SELECT id, name, address, mobile_no AS mobileNo, salary, date_of_birth AS dob, is_active AS active FROM employee WHERE id = ?
example.queries.updateByValue = UPDATE employee SET name = ?, mobile_no = ? WHERE id = ?
example.queries.deleteByValue = DELETE FROM employee WHERE id = ?


assets.query.findAll = SELECT asset_id, emp_id, asset_details FROM assets
assets.query.findByEmpId = SELECT asset_id, emp_id, asset_details FROM assets WHERE emp_id = ?
assets.query.findByEmpIdJson = SELECT asset_id, emp_id, asset_details FROM assets_json WHERE emp_id = ?

assets.query.findByEmpIdPDF = SELECT emp_id,file_name,resume_pdf FROM employee_resume WHERE emp_id = ?
assets.query.savePDF= INSERT INTO employee_resume (emp_id, file_name, resume_pdf) VALUES (?, ?, ?)

assets.query.getAudio= SELECT audio_id ,emp_id, file_name, content_type,audio_data FROM employee_audio WHERE audio_id =?
assets.query.saveAudio= INSERT INTO employee_audio (emp_id, file_name, content_type, audio_data) VALUES (?, ?, ?, ?)


assets.query.getVideo= SELECT vid_id ,emp_id, file_name, content_type,vid_data FROM employee_video WHERE emp_id =?
assets.query.saveVideo= INSERT INTO employee_video (emp_id, file_name, content_type, vid_data) VALUES (?, ?, ?, ?)

aes.secret.key = 1234567890123456
bank.query.findByUsername =SELECT crn, emp_id, username_plain, password_hash FROM employee_bank_details WHERE username_plain = ?;
bank.query.findEmployeeBankDetail =SELECT crn, emp_id, username_encrypted, password_hash, acc_no_hash, acc_no_last4, acc_no_masked, acc_type, username_plain FROM employee_bank_details WHERE emp_id = ?
bank.query.saveEmployeeBankDetail=INSERT INTO employee_bank_details (emp_id, username_encrypted, password_hash, acc_no_hash, acc_no_last4, acc_no_masked, acc_type, username_plain) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
bank.query.findByUsernameHash= SELECT crn,emp_id, username_encrypted, password_hash FROM employee_bank_details WHERE username_encrypted = ?
